### ISSUE TITLE
[bug] DTO refactor broke Swagger generation

### ISSUE THREAD

**Issue by JoeCap08055** [AmplicaLabs/account-service#70]
Since #66 was merged, the `api` service does not run due to broken Swagger generation.

Also broken in the CI pipeline for generating/publishing the swagger docs.

Probably should have something in the PR pipeline to catch this... unit & e2e tests ran, but the app doesn't run 😞 

```
[Nest] 64883  - 04/26/2024, 1:29:19 PM     LOG [main] ****** MAIN CATCH ********
[Nest] 64883  - 04/26/2024, 1:29:19 PM   ERROR [main] TypeError: Cannot set properties of undefined (setting '_OPENAPI_METADATA_FACTORY')
[Nest] 64883  - 04/26/2024, 1:29:19 PM   ERROR [main] TypeError: Cannot set properties of undefined (setting '_OPENAPI_METADATA_FACTORY')
    at /Users/joecaputo/src/AmplicaLabs/account-service/node_modules/@nestjs/swagger/dist/plugin/metadata-loader.js:40:70
    at Array.map (<anonymous>)
    at MetadataLoader.<anonymous> (/Users/joecaputo/src/AmplicaLabs/account-service/node_modules/@nestjs/swagger/dist/plugin/metadata-loader.js:38:39)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/joecaputo/src/AmplicaLabs/account-service/node_modules/@nestjs/swagger/dist/plugin/metadata-loader.js:5:58)
```

**Comment by mattheworris** [comment]
The metadata generation needs to run. I have a fix in my branch that will merge next.
